// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env['npm_package_version'],
  firebaseToken:
    '1//0geGdpWBIc4UaCgYIARAAGBASNwF-L9IrSdVgAT3zdB7VokPGN1AyQeosWqFxQ50WGr9r-xVhgOjEcV1gDDHYtjgNFbk9t7d5xf4',
  serverUrl: 'https://tirtajaya.vip/api',
  defaultLanguage: 'id-ID',
  supportedLanguages: ['en-US', 'id-ID'],
};
