export class PassengerModel {
  package_id!: number;
  sender_id!: number;
  sender: any;
  recipient_id!: number;
  recipient: any;
  city_id!: number;
  city: any;
  employee_id!: number;
  category_id!: number;
  go_send_id!: number;
  description!: string;
  cost!: number;
  discount!: number;
  payment!: number;
  koli!: number;
  origin_from!: string;
  level!: string;
  request!: string;
  request_description!: string;
  note!: string;
  status!: string;
  status_package!: string;
  resi_number!: string;
  photo!: string;
  print!: number;
  move_time!: Date;
  book_date!: Date;
  send_date!: Date;
  check_payment!: string;
  check_sp!: string;
  check_date_sp!: Date;
  taking_time!: Date;
  taking_by!: string;
  taking_status!: boolean;
  office!: string;
  isCreateSP!: boolean;

  setPackage(_passenger: unknown) {
    const passenger = _passenger as PassengerModel;
    this.package_id = passenger.package_id;
    this.sender_id = passenger.sender_id;
    this.recipient_id = passenger.recipient_id;
    this.city_id = passenger.city_id;
    (this.city = passenger.city), (this.employee_id = passenger.employee_id);
    this.category_id = passenger.category_id;
    this.go_send_id = passenger.go_send_id;
    this.description = passenger.description || '';
    this.cost = passenger.cost;
    this.discount = passenger.discount;
    this.payment = passenger.payment;
    this.koli = passenger.koli;
    this.origin_from = passenger.origin_from || '';
    this.level = passenger.level || '';
    this.request = passenger.request || '';
    this.request_description = passenger.request_description || '';
    this.note = passenger.note;
    this.status = passenger.status || '';
    this.status_package = passenger.status_package || '';
    this.resi_number = passenger.resi_number || '';
    this.photo = passenger.photo || '';
    this.print = passenger.print;
    this.move_time = passenger.move_time;
    this.book_date = passenger.book_date || '';
    this.send_date = passenger.send_date || '';
    this.check_payment = passenger.check_payment || '';
    this.check_sp = passenger.check_sp || '';
    this.check_date_sp = passenger.check_date_sp || '';
    this.taking_time = passenger.taking_time || '';
    this.taking_by = passenger.taking_by || '';
    this.taking_status = passenger.taking_status;
    this.office = passenger.office || '';
  }
}
